spring.application.name=Ride_LocationService

spring.datasource.url= jdbc:mysql://localhost:3306/App_Db_Local
spring.datasource.username=root
spring.datasource.password=Vivek1510@#
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = validate
server.port=8083
